from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import TimeSeriesSplit


# =========================================================
# PROJECT CONFIGURATION
# =========================================================

SEED = 42
SEASONAL_WEEKS = 52
TEST_YEAR = 2025
FORECAST_HORIZON = 8

PROJECT_ROOT = Path(__file__).resolve().parent.parent

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

CLEANED_FILE = PROCESSED_DIR / "cleaned_sales.csv"
WEEKLY_FILE = PROCESSED_DIR / "weekly_demand.csv"
BASELINE_FILE = PROCESSED_DIR / "seasonal_naive_2025.csv"
FORECAST_FILE = PROCESSED_DIR / "future_8_week_forecast.csv"


# =========================================================
# WAPE
# =========================================================

def calculate_wape(y_true, y_pred):
    """
    Weighted Absolute Percentage Error.
    """

    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)

    denominator = np.sum(np.abs(y_true))

    if denominator == 0:
        return np.nan

    return (
        np.sum(np.abs(y_true - y_pred))
        / denominator
    ) * 100


# =========================================================
# LOAD CLEANED SALES DATA
# =========================================================

def load_cleaned_sales():
    """
    Load the cleaned sales dataset generated by pipeline.py.
    """

    if not CLEANED_FILE.exists():
        raise FileNotFoundError(
            f"Cleaned dataset not found:\n{CLEANED_FILE}\n\n"
            "Run pipeline.py first."
        )

    df = pd.read_csv(CLEANED_FILE)

    df["date"] = pd.to_datetime(
        df["date"],
        errors="coerce"
    )

    if df["date"].isna().any():
        raise ValueError(
            "Invalid dates found in cleaned_sales.csv."
        )

    return df


# =========================================================
# CREATE WEEKLY SKU DEMAND
# =========================================================

def create_weekly_demand(df):
    """
    Convert transaction-level sales into weekly SKU demand.
    """

    df = df.copy()

    # Same weekly definition used in the final notebook.
    df["week"] = (
        df["date"]
        .dt.to_period("W-MON")
        .apply(lambda x: x.start_time)
    )

    weekly_demand = (
        df.groupby(
            ["week", "sku_id"],
            as_index=False
        )
        .agg(
            weekly_quantity=("quantity", "sum"),
            weekly_sales=("total_value", "sum")
        )
    )

    weekly_demand = (
        weekly_demand
        .sort_values(["sku_id", "week"])
        .reset_index(drop=True)
    )

    return weekly_demand


# =========================================================
# COMPLETE SKU-WEEK GRID
# =========================================================

def complete_sku_week_grid(weekly_demand):
    """
    Create a complete weekly grid for every SKU.

    Weeks with no transactions are represented as zero demand.
    """

    all_weeks = pd.date_range(
        weekly_demand["week"].min(),
        weekly_demand["week"].max(),
        freq="7D"
    )

    all_skus = weekly_demand["sku_id"].unique()

    complete_index = pd.MultiIndex.from_product(
        [all_weeks, all_skus],
        names=["week", "sku_id"]
    )

    weekly_complete = (
        weekly_demand
        .set_index(["week", "sku_id"])
        .reindex(complete_index)
        .reset_index()
    )

    weekly_complete["weekly_quantity"] = (
        weekly_complete["weekly_quantity"]
        .fillna(0)
    )

    weekly_complete["weekly_sales"] = (
        weekly_complete["weekly_sales"]
        .fillna(0)
    )

    return weekly_complete


# =========================================================
# SAVE WEEKLY DEMAND
# =========================================================

def save_weekly_demand(weekly_demand):
    """
    Save the analysis-ready weekly SKU demand dataset.
    """

    PROCESSED_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    weekly_demand.to_csv(
        WEEKLY_FILE,
        index=False
    )


# =========================================================
# SEASONAL-NAIVE BASELINE
# =========================================================

def create_seasonal_naive_baseline(
    weekly,
    test_year=TEST_YEAR
):
    """
    Seasonal-naive baseline:
    demand for a test week = demand from the same week
    52 weeks earlier.
    """

    weekly = weekly.copy()

    test = weekly[
        weekly["week"].dt.year == test_year
    ][
        ["week", "sku_id", "weekly_quantity"]
    ].copy()

    lookup = (
        weekly
        .set_index(["sku_id", "week"])
        ["weekly_quantity"]
    )

    baseline_forecasts = []

    for sku, week in zip(
        test["sku_id"],
        test["week"]
    ):
        previous_week = (
            week
            - pd.Timedelta(
                weeks=SEASONAL_WEEKS
            )
        )

        baseline_forecasts.append(
            lookup.get(
                (sku, previous_week),
                np.nan
            )
        )

    test["baseline_forecast"] = (
        baseline_forecasts
    )

    valid = test[
        "baseline_forecast"
    ].notna()

    comparison = test.loc[
        valid
    ].copy()

    baseline_wape = calculate_wape(
        comparison["weekly_quantity"],
        comparison["baseline_forecast"]
    )

    return test, baseline_wape


# =========================================================
# FEATURE ENGINEERING
# =========================================================

def create_features(weekly):
    """
    Create time-aware forecasting features.

    Rolling features are shifted first so the current
    target is never included.
    """

    g = (
        weekly
        .sort_values(["sku_id", "week"])
        .copy()
    )

    # Lag features
    g["lag_1"] = (
        g.groupby("sku_id")
        ["weekly_quantity"]
        .shift(1)
    )

    g["lag_2"] = (
        g.groupby("sku_id")
        ["weekly_quantity"]
        .shift(2)
    )

    g["lag_4"] = (
        g.groupby("sku_id")
        ["weekly_quantity"]
        .shift(4)
    )

    g["lag_8"] = (
        g.groupby("sku_id")
        ["weekly_quantity"]
        .shift(8)
    )

    g["lag_52"] = (
        g.groupby("sku_id")
        ["weekly_quantity"]
        .shift(52)
    )

    # Rolling features
    g["rolling_mean_4"] = (
        g.groupby("sku_id")
        ["weekly_quantity"]
        .transform(
            lambda s:
            s.shift(1)
            .rolling(
                4,
                min_periods=4
            )
            .mean()
        )
    )

    g["rolling_mean_8"] = (
        g.groupby("sku_id")
        ["weekly_quantity"]
        .transform(
            lambda s:
            s.shift(1)
            .rolling(
                8,
                min_periods=8
            )
            .mean()
        )
    )

    # Calendar features
    g["week_of_year"] = (
        g["week"]
        .dt.isocalendar()
        .week
        .astype(int)
    )

    g["month"] = (
        g["week"]
        .dt.month
    )

    g["quarter"] = (
        g["week"]
        .dt.quarter
    )

    g["season"] = (
        g["month"]
        .map(
            {
                12: "Winter",
                1: "Winter",
                2: "Winter",
                3: "Spring",
                4: "Spring",
                5: "Spring",
                6: "Summer",
                7: "Summer",
                8: "Summer",
                9: "Autumn",
                10: "Autumn",
                11: "Autumn"
            }
        )
    )

    feature_cols = [
        "lag_1",
        "lag_2",
        "lag_4",
        "lag_8",
        "lag_52",
        "rolling_mean_4",
        "rolling_mean_8",
        "week_of_year",
        "month",
        "quarter",
        "season"
    ]

    model_df = g.dropna(
        subset=[
            "lag_52",
            "rolling_mean_4",
            "rolling_mean_8"
        ]
    ).copy()

    return model_df, feature_cols


# =========================================================
# TRAIN / TEST SPLIT
# =========================================================

def chronological_split(
    model_df,
    feature_cols,
    test_year=TEST_YEAR
):
    """
    Use all pre-2025 observations for training and
    2025 observations for testing.
    """

    train = model_df[
        model_df["week"].dt.year < test_year
    ].copy()

    test = model_df[
        model_df["week"].dt.year == test_year
    ].copy()

    if train.empty or test.empty:
        raise ValueError(
            "Training or test data is empty."
        )

    if train["week"].max() >= test["week"].min():
        raise ValueError(
            "Chronological split failed."
        )

    X_train = pd.get_dummies(
        train[feature_cols],
        columns=["season"],
        dtype=float
    )

    X_test = pd.get_dummies(
        test[feature_cols],
        columns=["season"],
        dtype=float
    ).reindex(
        columns=X_train.columns,
        fill_value=0
    )

    y_train = (
        train["weekly_quantity"]
        .astype(float)
    )

    y_test = (
        test["weekly_quantity"]
        .astype(float)
    )

    return (
        train,
        test,
        X_train,
        X_test,
        y_train,
        y_test
    )


# =========================================================
# TRAIN FINAL RANDOM FOREST
# =========================================================

def train_model(
    X_train,
    y_train
):
    """
    Train the same Random Forest configuration used
    in the final D3 notebook.
    """

    model = RandomForestRegressor(
        n_estimators=30,
        random_state=SEED,
        n_jobs=-1,
        min_samples_leaf=2,
        max_samples=0.30
    )

    model.fit(
        X_train,
        y_train
    )

    return model


# =========================================================
# MODEL EVALUATION
# =========================================================

def evaluate_model(
    model,
    X_test,
    y_test
):
    """
    Evaluate model using WAPE, MAE, RMSE and bias.
    """

    y_pred = np.maximum(
        model.predict(X_test),
        0
    )

    model_wape = calculate_wape(
        y_test,
        y_pred
    )

    model_mae = mean_absolute_error(
        y_test,
        y_pred
    )

    model_rmse = np.sqrt(
        mean_squared_error(
            y_test,
            y_pred
        )
    )

    model_bias = float(
        np.mean(
            y_pred
            - y_test.to_numpy()
        )
    )

    return (
        y_pred,
        model_wape,
        model_mae,
        model_rmse,
        model_bias
    )


# =========================================================
# FAIR BASELINE COMPARISON
# =========================================================

def compare_with_baseline(
    weekly,
    test,
    y_pred
):
    """
    Compare Random Forest and seasonal-naive on
    the same eligible test rows.
    """

    lookup = (
        weekly
        .set_index(["sku_id", "week"])
        ["weekly_quantity"]
    )

    test_copy = test.copy()

    baseline_values = []

    for sku, week in zip(
        test_copy["sku_id"],
        test_copy["week"]
    ):
        previous_week = (
            week
            - pd.Timedelta(
                weeks=SEASONAL_WEEKS
            )
        )

        baseline_values.append(
            lookup.get(
                (sku, previous_week),
                np.nan
            )
        )

    test_copy["baseline_forecast"] = (
        baseline_values
    )

    valid = (
        test_copy["baseline_forecast"]
        .notna()
    )

    comparison = test_copy.loc[
        valid
    ].copy()

    comparison["model_forecast"] = (
        y_pred[valid.to_numpy()]
    )

    baseline_wape = calculate_wape(
        comparison["weekly_quantity"],
        comparison["baseline_forecast"]
    )

    model_wape = calculate_wape(
        comparison["weekly_quantity"],
        comparison["model_forecast"]
    )

    improvement = (
        baseline_wape
        - model_wape
    )

    return (
        comparison,
        baseline_wape,
        model_wape,
        improvement
    )


# =========================================================
# ROLLING-ORIGIN CROSS VALIDATION
# =========================================================

def rolling_origin_validation(
    train,
    feature_cols
):
    """
    Five-fold rolling-origin validation on the
    pre-2025 training history.
    """

    cv_base = (
        train
        .sort_values("week")
        .copy()
    )

    unique_weeks = np.array(
        sorted(
            cv_base["week"].unique()
        )
    )

    if len(unique_weeks) < 10:
        raise ValueError(
            "Not enough historical weeks for "
            "rolling-origin CV."
        )

    n_splits = min(
        5,
        len(unique_weeks) // 2
    )

    tscv = TimeSeriesSplit(
        n_splits=n_splits
    )

    cv_rows = []

    for fold, (
        train_indices,
        test_indices
    ) in enumerate(
        tscv.split(unique_weeks),
        start=1
    ):

        train_weeks = set(
            unique_weeks[
                train_indices
            ]
        )

        test_weeks = set(
            unique_weeks[
                test_indices
            ]
        )

        fold_train = cv_base[
            cv_base["week"].isin(
                train_weeks
            )
        ]

        fold_test = cv_base[
            cv_base["week"].isin(
                test_weeks
            )
        ]

        X_train = pd.get_dummies(
            fold_train[feature_cols],
            columns=["season"],
            dtype=float
        )

        X_test = pd.get_dummies(
            fold_test[feature_cols],
            columns=["season"],
            dtype=float
        ).reindex(
            columns=X_train.columns,
            fill_value=0
        )

        model = train_model(
            X_train,
            fold_train["weekly_quantity"]
        )

        predictions = np.maximum(
            model.predict(X_test),
            0
        )

        cv_rows.append(
            {
                "fold": fold,
                "train_end": fold_train["week"].max(),
                "test_start": fold_test["week"].min(),
                "test_end": fold_test["week"].max(),
                "MAE": mean_absolute_error(
                    fold_test["weekly_quantity"],
                    predictions
                ),
                "RMSE": np.sqrt(
                    mean_squared_error(
                        fold_test["weekly_quantity"],
                        predictions
                    )
                ),
                "WAPE": calculate_wape(
                    fold_test["weekly_quantity"],
                    predictions
                )
            }
        )

    cv_results = pd.DataFrame(
        cv_rows
    )

    mean_wape = (
        cv_results["WAPE"]
        .mean()
    )

    return (
        cv_results,
        mean_wape
    )


# =========================================================
# LEAKAGE CHECK
# =========================================================

def leakage_check(
    model_df,
    train,
    test,
    feature_cols
):
    """
    Confirm chronological separation and that
    engineered lag/rolling features exist.
    """

    if train["week"].max() >= test["week"].min():
        raise AssertionError(
            "Leakage detected in train/test split."
        )

    required_history_features = [
        "lag_1",
        "lag_2",
        "lag_4",
        "lag_8",
        "lag_52",
        "rolling_mean_4",
        "rolling_mean_8"
    ]

    for column in required_history_features:
        if column not in feature_cols:
            raise AssertionError(
                f"Missing feature: {column}"
            )

    if model_df[
        required_history_features
    ].isna().any().any():
        raise AssertionError(
            "Missing values found in model features."
        )

    return True


# =========================================================
# RECURSIVE 8-WEEK FORECAST
# =========================================================

def create_future_forecast(
    weekly,
    model,
    X_train_columns,
    feature_cols,
    horizon=FORECAST_HORIZON
):
    """
    Generate an 8-week recursive forecast for every SKU
    with sufficient history.
    """

    history = (
        weekly[
            [
                "sku_id",
                "week",
                "weekly_quantity"
            ]
        ]
        .copy()
        .sort_values(
            ["sku_id", "week"]
        )
    )

    last_week = (
        history["week"].max()
    )

    skus = (
        history["sku_id"]
        .unique()
    )

    future_weeks = [
        last_week
        + pd.Timedelta(weeks=i)
        for i in range(
            1,
            horizon + 1
        )
    ]

    future_rows = []

    series = {
        sku: list(
            zip(
                group["week"].tolist(),
                group["weekly_quantity"]
                .astype(float)
                .tolist()
            )
        )
        for sku, group
        in history.groupby("sku_id")
    }

    season_map = {
        12: "Winter",
        1: "Winter",
        2: "Winter",
        3: "Spring",
        4: "Spring",
        5: "Spring",
        6: "Summer",
        7: "Summer",
        8: "Summer",
        9: "Autumn",
        10: "Autumn",
        11: "Autumn"
    }

    for week in future_weeks:

        for sku in skus:

            values = {
                w: v
                for w, v
                in series[sku]
            }

            def get_lag(n):
                return values.get(
                    week
                    - pd.Timedelta(weeks=n),
                    np.nan
                )

            recent_4 = [
                get_lag(i)
                for i in range(1, 5)
            ]

            recent_8 = [
                get_lag(i)
                for i in range(1, 9)
            ]

            row = {
                "sku_id": sku,
                "week": week,
                "lag_1": get_lag(1),
                "lag_2": get_lag(2),
                "lag_4": get_lag(4),
                "lag_8": get_lag(8),
                "lag_52": get_lag(52),
                "rolling_mean_4": (
                    np.mean(recent_4)
                    if all(
                        pd.notna(
                            recent_4
                        )
                    )
                    else np.nan
                ),
                "rolling_mean_8": (
                    np.mean(recent_8)
                    if all(
                        pd.notna(
                            recent_8
                        )
                    )
                    else np.nan
                ),
                "week_of_year": int(
                    week
                    .isocalendar()
                    .week
                ),
                "month": week.month,
                "quarter": week.quarter,
                "season": season_map[
                    week.month
                ]
            }

            future_rows.append(row)

        # Predict this week before moving
        # to the next week. Previous model
        # predictions then become history.
        current_step = pd.DataFrame(
            [
                row
                for row in future_rows
                if row["week"] == week
            ]
        )

        usable = current_step.dropna(
            subset=[
                "lag_52",
                "rolling_mean_4",
                "rolling_mean_8"
            ]
        ).copy()

        if not usable.empty:

            X_future = pd.get_dummies(
                usable[feature_cols],
                columns=["season"],
                dtype=float
            ).reindex(
                columns=X_train_columns,
                fill_value=0
            )

            predictions = np.maximum(
                model.predict(X_future),
                0
            )

            for sku, prediction in zip(
                usable["sku_id"],
                predictions
            ):
                series[sku].append(
                    (
                        week,
                        float(prediction)
                    )
                )

    future_forecast = pd.DataFrame(
        future_rows
    )

    forecast_lookup = {
        (sku, week): value
        for sku, values in series.items()
        for week, value in values
    }

    future_forecast[
        "forecast_demand"
    ] = [
        forecast_lookup.get(
            (sku, week),
            np.nan
        )
        for sku, week
        in zip(
            future_forecast["sku_id"],
            future_forecast["week"]
        )
    ]

    return future_forecast


# =========================================================
# MAIN FORECASTING PIPELINE
# =========================================================

def run_forecasting():

    print("=" * 60)
    print("FORESIGHT FORECASTING PIPELINE")
    print("=" * 60)

    # -----------------------------------------------------
    # 1. Load cleaned data
    # -----------------------------------------------------
    print("\n1. Loading cleaned sales data...")

    df = load_cleaned_sales()

    print(
        f"Loaded rows: {len(df)}"
    )

    # -----------------------------------------------------
    # 2. Weekly aggregation
    # -----------------------------------------------------
    print("\n2. Creating weekly SKU demand...")

    weekly_demand = create_weekly_demand(
        df
    )

    print(
        f"Weekly demand rows: "
        f"{len(weekly_demand)}"
    )

    # -----------------------------------------------------
    # 3. Complete SKU-week grid
    # -----------------------------------------------------
    print("\n3. Completing SKU-week grid...")

    weekly = complete_sku_week_grid(
        weekly_demand
    )

    weekly = (
        weekly
        .sort_values(
            ["sku_id", "week"]
        )
        .reset_index(drop=True)
    )

    print(
        f"Unique SKUs: "
        f"{weekly['sku_id'].nunique()}"
    )

    print(
        f"Number of weeks: "
        f"{weekly['week'].nunique()}"
    )

    # -----------------------------------------------------
    # 4. Save weekly demand
    # -----------------------------------------------------
    save_weekly_demand(
        weekly
    )

    print(
        f"Weekly demand saved to:\n"
        f"{WEEKLY_FILE}"
    )

    # -----------------------------------------------------
    # 5. Seasonal-naive baseline
    # -----------------------------------------------------
    print("\n4. Building seasonal-naive baseline...")

    baseline, baseline_wape = (
        create_seasonal_naive_baseline(
            weekly
        )
    )

    baseline.to_csv(
        BASELINE_FILE,
        index=False
    )

    print(
        f"Seasonal-naive WAPE: "
        f"{baseline_wape:.2f}%"
    )

    print(
        f"Baseline saved to:\n"
        f"{BASELINE_FILE}"
    )

    # -----------------------------------------------------
    # 6. Feature engineering
    # -----------------------------------------------------
    print("\n5. Creating forecasting features...")

    model_df, feature_cols = (
        create_features(
            weekly
        )
    )

    print(
        f"Model rows: {len(model_df)}"
    )

    # -----------------------------------------------------
    # 7. Chronological train/test split
    # -----------------------------------------------------
    print("\n6. Creating chronological train/test split...")

    (
        train,
        test,
        X_train,
        X_test,
        y_train,
        y_test
    ) = chronological_split(
        model_df,
        feature_cols
    )

    print(
        f"Train: "
        f"{train['week'].min().date()} "
        f"to "
        f"{train['week'].max().date()}"
    )

    print(
        f"Test : "
        f"{test['week'].min().date()} "
        f"to "
        f"{test['week'].max().date()}"
    )

    print(
        "Chronological split: PASS"
    )

    # -----------------------------------------------------
    # 8. Train Random Forest
    # -----------------------------------------------------
    print("\n7. Training Random Forest model...")

    model = train_model(
        X_train,
        y_train
    )

    print(
        "Random Forest training completed."
    )

    # -----------------------------------------------------
    # 9. Evaluate final test set
    # -----------------------------------------------------
    print("\n8. Evaluating model...")

    (
        y_pred,
        model_wape,
        model_mae,
        model_rmse,
        model_bias
    ) = evaluate_model(
        model,
        X_test,
        y_test
    )

    print(
        f"Model WAPE: {model_wape:.2f}%"
    )

    print(
        f"MAE: {model_mae:.4f}"
    )

    print(
        f"RMSE: {model_rmse:.4f}"
    )

    print(
        f"Bias: {model_bias:.4f}"
    )

    # -----------------------------------------------------
    # 10. Fair baseline comparison
    # -----------------------------------------------------
    print("\n9. Comparing model with seasonal-naive...")

    (
        comparison,
        fair_baseline_wape,
        fair_model_wape,
        improvement
    ) = compare_with_baseline(
        weekly,
        test,
        y_pred
    )

    print(
        f"Seasonal-naive WAPE: "
        f"{fair_baseline_wape:.2f}%"
    )

    print(
        f"Model WAPE (same rows): "
        f"{fair_model_wape:.2f}%"
    )

    print(
        f"Improvement: "
        f"{improvement:.2f} percentage points"
    )

    # -----------------------------------------------------
    # 11. Rolling-origin validation
    # -----------------------------------------------------
    print("\n10. Running rolling-origin validation...")

    (
        cv_results,
        mean_cv_wape
    ) = rolling_origin_validation(
        train,
        feature_cols
    )

    print(
        cv_results
    )

    print(
        f"\nMean rolling WAPE: "
        f"{mean_cv_wape:.2f}%"
    )

    # -----------------------------------------------------
    # 12. Leakage audit
    # -----------------------------------------------------
    print("\n11. Running leakage audit...")

    leakage_check(
        model_df,
        train,
        test,
        feature_cols
    )

    print(
        "Leakage audit: PASS"
    )

    # -----------------------------------------------------
    # 13. Eight-week forward forecast
    # -----------------------------------------------------
    print("\n12. Creating 8-week forward forecast...")

    future_forecast = create_future_forecast(
        weekly=weekly,
        model=model,
        X_train_columns=X_train.columns,
        feature_cols=feature_cols,
        horizon=FORECAST_HORIZON
    )

    future_forecast.to_csv(
        FORECAST_FILE,
        index=False
    )

    print(
        f"Future forecast saved to:\n"
        f"{FORECAST_FILE}"
    )

    print(
        f"Rows: "
        f"{len(future_forecast)}"
    )

    print(
        f"Weeks: "
        f"{future_forecast['week'].nunique()}"
    )

    print(
        f"SKUs: "
        f"{future_forecast['sku_id'].nunique()}"
    )

    # -----------------------------------------------------
    # 14. Final checks
    # -----------------------------------------------------
    print("\n13. Final D3 checks...")

    checks = {
        "Weekly SKU forecast":
            weekly.groupby(
                ["week", "sku_id"]
            ).size().max() == 1,

        "Seasonal-naive baseline":
            pd.notna(fair_baseline_wape),

        "Rolling-origin CV":
            len(cv_results) >= 2,

        "WAPE comparison":
            pd.notna(fair_model_wape)
            and pd.notna(fair_baseline_wape),

        "No leakage":
            train["week"].max()
            < test["week"].min(),

        "8-week forward forecast":
            future_forecast[
                "week"
            ].nunique() == FORECAST_HORIZON
    }

    for name, passed in checks.items():

        status = (
            "PASS"
            if passed
            else "FAIL"
        )

        print(
            f"{name}: {status}"
        )

    assert all(
        checks.values()
    )

    print(
        "\nD3 FINAL ACCEPTANCE: PASS"
    )

    print("=" * 60)

    return {
        "weekly_demand": weekly,
        "baseline": baseline,
        "model": model,
        "test_predictions": comparison,
        "cv_results": cv_results,
        "future_forecast": future_forecast
    }


# =========================================================
# RUN DIRECTLY
# =========================================================

if __name__ == "__main__":
    run_forecasting()